site_name: Your Project Name

nav:
  - Home: index.md
  - Backend: backend.md
  - Database: database.md
  - Frontend: frontend.md
  - Setup Instructions: setup.md
  - Testing: testing.md
  - Team: team.md
  - Future Improvements: future.md
